### ISSUE TITLE
Delete/Update commands not working?

### ISSUE THREAD

**Issue by rsteinmann** [cubesql/clients#11]
Hey,
today I've started to write a little PHP script that should help me maintain my database. By testing different SQL commands I've found out, that the script is not updating or deleting anything.

#### 1st Try using the select method
I've used the following command
```
$OBJ->select("DELETE FROM b_buchungen WHERE rowid=25;");
```
It returns me the errorMessage:
*Error from server: 'Wrong context for the requested operation.'*

#### 2nd Try using the execute command
```
$OBJ->execute("DELETE FROM b_buchungen WHERE rowid=25;");
```

It returns me nothing at all and the Object holds no error. Also the record is still existing.

#### Further Informations
Same happens if I try to update a record. Either the context is wrong or the operation is not executed.

If I use any select queries or database info / table info, it works perfectly.

I wonder what this could be. I've checked the privileges, but I could not find any restrictions (they are marked with the * symbol).

Do I do something wrong? Or did I break your script with one of my updates? Have you tested this functionality before?

Any info/help would be very much appreciated! Thanks!

**Comment by marcobambini** [comment]
Have you executed a **USE DATABASE dbName** before?

**Comment by rsteinmann** [comment]
Yes I'm connected by the *connect_database* command that does this for me. If I select a record from a table this works fine.

In general: Do I have to use the execute-method for writing operations?

**Comment by marcobambini** [comment]
You need to use execute method for INSERT/DELETE and UPDATE.
Since server is in autotransaction mode you need to COMMIT a write operation (or a series of write operations) in order to save changes.

**Comment by rsteinmann** [comment]
Okay, good to know. So then I have no clue why it's not working. I've checked all my commited code to your script in the version history, but I've never changed any network code or code within the execute-method. So it should not be any bad code there.

As a next step I'll check my SQL-Syntax to figure out it is 100% correct by using it within another software like the *SQLite Studio*...

**Comment by rsteinmann** [comment]
Okey I've tested the following command:
```
UPDATE b_buchungen SET BU_NOTIZ='test' WHERE rowid=25;
```
in SQLite Studio (on a local database not CubeSQL Server) it worked.

In my PHP Script it did not work with the execute command. (I've copy'n'pasted it)
