### ISSUE TITLE
cubesql_cursor_cstring and cubesql_cursor_cstring_static do not differ between NULL and Empty-String

### ISSUE THREAD

**Issue by dape82** [cubesql/clients#14]
The API-Functions cubesql_cursor_cstring and cubesql_cursor_cstring_static return a NULL-Pointer when the field contains an empty string.

The lines:
`if ((field == NULL) || (len <= 0)) return NULL;`

should be 

`if ((field == NULL) || (len < 0)) return NULL;`

I think that should fix the problem.

**Comment by marcobambini** [comment]
Thanks a lot @dape82 , I added your fix and a couple more in the latest commit.
