### ISSUE TITLE
Depricated Warnings in PHP7

### ISSUE THREAD

**Issue by rsteinmann** [cubesql/clients#2]
After including the native `cubeSQLServer.php` in my PHP project it displayed 3 errors to me:
![cubesql-php-errors](https://cloud.githubusercontent.com/assets/3932097/23716249/d6a4f13a-042f-11e7-96ae-2f0290e4e1de.PNG)

The reason was that the used constructors are [PHP4 constructors](http://php.net/manual/en/migration70.deprecated.php) that got depricated in the PHP7 Versions.

More about constructors in the [PHP reference](http://php.net/manual/en/language.oop5.decon.php)

I've solved these warnings by replacing the named methods with the `__construct` method and opened a pull request.

**Comment by rsteinmann** [comment]
I have tested my changes also with the PHP Version 5.6.30 without any conflicts.

**Comment by marcobambini** [comment]
Very well done @rsteinmann, thanks a lot for your contribution.
