### ISSUE TITLE
Errors are passed incorrect from csqldb Object

### ISSUE THREAD

**Issue by rsteinmann** [cubesql/clients#3]
After experimenting with the php native connector I've figured out that errors that occur within the `csqldb` Object are not passed through the `cubeSQLServer` Object. So checking for errors always returned false in that case:

![cubesql-phpconnector-errorstack](https://cloud.githubusercontent.com/assets/3932097/23756734/e06d3bc2-04e4-11e7-882a-19dd91145cc8.PNG)

The reason was that the defined properties of the csqldb object were called `errcode` and `errmsg` while the exception handler created new properties called `errorcode` and `errormsg`.

In the upcoming pull request I've changed the properties to `errorcode` and `errormsg` and fixed the referencing of the cubeSQLServer methods to point to the same.

After that the errors get passed correctly:

![cubesql-phpconnector-errorstack-fixed](https://cloud.githubusercontent.com/assets/3932097/23756927/9a7224c4-04e5-11e7-8fdf-74b8e359a836.PNG)

I checked the code for further occurrences of the terms `errcode` and `errmsg` but none were left so the error-handling should be correct now for all types of errors.

**Comment by marcobambini** [comment]
Very good catch, thanks a lot!
