### ISSUE TITLE
Error opening database that has a space character in it.

### ISSUE THREAD

**Issue by rsteinmann** [cubesql/clients#7]
I tried to access a database from a software we use in our company. The manufacturer called that database `Lodgit Database.lxdb`. I wasn't able to access it with the connector and another Freeware Software.  I got the error:

![cubesql-phpconnector-error-accessing-db](https://cloud.githubusercontent.com/assets/3932097/23762127/5d24b4aa-04f5-11e7-9f95-aeb196e12dd7.PNG)

After some tryouts I've found out that it's possible to access a newly created database called `Test`. So I tried to open the database with the following script:
```php
// Connection infos
$host = '192.168.22.3';
$port = 4430;
$user = 'admin';
$pass = 'admin';
$database = 'Lodgit Test Database.lxdb';
//$database = 'Test';
// Setup Connection
$cdb = new cubeSQLServer;
$cdb->connect_database($host, $port, $user, $pass, $database, 25);
$selectdb = $cdb->execute('USE DATABASE "'.$database.'";');
$tables = $cdb->select("SHOW TABLES");
```
And it worked. It also worked for the `Test` database.

So I wanted to suggest to change the following line in the `connect_database`  method of the cubeSQLServer object.

**FROM**
`$this->db->send_statement($kCOMMAND_EXECUTE, "USE DATABASE $database;");`

**TO**
`$this->db->send_statement($kCOMMAND_EXECUTE, 'USE DATABASE "'.$database.'";');`

It will send that query always like that: `USE DATABASE "database name with spaces";` to the server.

@marcobambini If you think that will cause no conflicts I will make up a new pull request. Just let me know.

Thanks a lot for the connector! Now I'm able to access our live-database using PHP! 👍

**Comment by marcobambini** [comment]
Hi @rsteinmann yes you can safely quote database name.
Thanks a lot for your invaluable contribution!

**Comment by rsteinmann** [comment]
Hi @marcobambini that's good.

You are very welcome. I'm glad that my work is useful! That connector saved me a lot of time since I have no experience in network programming. So thank you for your work!
