### ISSUE TITLE
Script incompatible with PHP5.3

### ISSUE THREAD

**Issue by rsteinmann** [cubesql/clients#9]
Hey,
today I did some quality testing of the script to figure out if everything works out well after the changes I've made. By testing the script in a php5.3 environment it displayed me syntax errors.

The reason was that the script is using function array dereferencing that was introduced in [php5.4](http://php.net/manual/en/migration54.new-features.php). So I made a little research if it makes sense to convert the script to be compatible to php5.3 versions.

As I've found out [here](https://wwphp-fb.github.io/articles/php-versions-usage/) php5.3 still seems to be in use by many webservers. However that research was made in Oct. 2014 and the 5.3 version of PHP has officially reached end of life.

Still I changed the code to see if after fixing these issues it would run in php5.3 and it does. It was just some lines of code to change to make the script compatbile to 5.3.

Do you want me to commit that @marcobambini ? Work is done already anyways and the script is also still compatible with the newest php7.1 version.

**Comment by marcobambini** [comment]
Hi @rsteinmann I found these updated stats: https://seld.be/notes/php-versions-stats-2016-1-edition
Seems like 2.43% are still using php5.3, I am not sure if it worths the update or not...
Can you please let me know what changed?

**Comment by rsteinmann** [comment]
Hi @marcobambini, okay so it does not seem to be too important. 

I've just made a pull request and commented on it so you can examine what I've changed. It's not a big update. You decide wether to update your script for PHP5.3 support or not ;-)
